name: Deploy the blog

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { token: "${{ secrets.GITHUB_TOKEN }}" }
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes
      - run: nix build .#blog
      - uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog-nobbz-dev
          directory: ./result
          # directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
