name: Deploy the blog

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { token: "${{ secrets.GITHUB_TOKEN }}" }
      - uses: DeterminateSystems/nix-installer-action@v9
        with: { github-token: "${{ github.token }}" }
      # - run: nix build .#blog
      - run: nix develop . -c deno task build
      - uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: blog-nobbz-dev
          # directory: ./result
          directory: ./_site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
